{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helloworldnodejs.fullname" . }}
  labels:
    {{- include "helloworldnodejs.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.service.portName }}
  to:
    kind: Service
    name: {{ include "helloworldnodejs.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
